import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "react-toastify/dist/ReactToastify.css";
import Head from "next/head";
import badgeImg from "@images/badge.png";

const poppins = Poppins({
  weight: ["100", "200", "300", "400", "500", "600", "700"],
  subsets: ["latin"],
});
import "@styles/style.scss";
import { ToastContainer } from "react-toastify";

export const metadata: Metadata = {
  title: "Al Application form - Mayurapada Central College",
  description: "Generated by create next app",
  icons: {
    icon: "/images/badge.png",
  },
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/images/badge.png" />
      </Head>
      <body className={poppins.className}>
        <ToastContainer
          position="bottom-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
        {children}
      </body>
    </html>
  );
}
